import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="h-screen">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}>
        <div className="relative z-10 h-screen overflow-auto overscroll-contain">
          <NavBar />
          <div className="pt-1 pb-8">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
